name: Publish documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --global user.mail doc@github.com
          git config --global user.name doc

      - name: Switch to gh-pages branch
        run: |
          git branch -f gh-pages
          git switch gh-pages

      - name: Build dev environment
        run: make dev

      - name: Build documentation
        run: make doc

      - name: Push to gh-pages branch
        run: |
          git add docs
          git commit -am 'docs: update'
          git push -f origin gh-pages
        if: github.event_name != 'pull_request'
